### PR TITLE
Allow Node engine version check to pass on Node.js 12

### PR DESCRIPTION
**Pull request by eszjay**

### CODE REVIEW

**Comment by dennisotugo** [comment]
@mikermcneil

**Comment by dennisotugo** [comment]
@sgress454 +1

**Comment by conghai** [comment]
+1

**Comment by conghai** [comment]
Drop node 4 support with configs `^6.0` => you was drop node 8, 10, 11, 12 too

Please change it too `>=6.0`

**Comment by dennisotugo** [comment]
So what is next :)

**Comment by rachaelshaw** [comment]
@eszjay thanks!

**Pull request merged**
